version: '3.7'

services:
    frontend:
        container_name: frontend
        build:
            context: .
            dockerfile: ./Dockerfile
            target: development
        volumes:
            - ./:/usr/src/frontend:cached
        ports:
            - '3002:80'
        tty: true
