export const SET_CATEGORIES_LIST = 'CATEGORY:SET_CATEGORIES_LIST';
export const ADD_CATEGORY = 'CATEGORY:ADDE_CATEGORY';
export const UPDATE_CATEGORY = 'CATEGORY:UPDATE_CATEGORY';
export const REMOVE_CATEGORY = 'CATEGORY:REMOVE_CATEGORY';
