export const SET_CATEGORY_LIST = 'CATEGORY:SET_CATEGORY_LIST';
export const ADD_CATEGORY = 'CATEGORY:ADDE_CATEGORY';
export const UPDATE_CATEGORY = 'CATEGORY:UPDATE_CATEGORY';
export const REMOVE_CATEGORY = 'CATEGORY:REMOVE_CATEGORY';
